//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laptopstr
{
    using System;
    using System.Collections.Generic;
    
    public partial class databarang
    {
        public int idbarang { get; set; }
        public string Nama { get; set; }
        public string Harga { get; set; }
        public string Stok { get; set; }
    }
}
